# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838ec147da090af26fb6a31f729592c77a91bd40d92be81b04c67c7c13dab7ac15d3c4a79eaf075bad9612c56e670d7ba0af31623464081ab70e9d699fa949b1

test:
  secret_key_base: 48b70ec59d7e19d2651ac52ba20d4f9c8930c7b8f344eb7a05519ddac57d400f14ec744bab77d188d7219b7b01e010beba46ea1445424016a3efd59c70e86c73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
